import { writable } from "svelte/store";

export let projectCardInfo = writable([
  {
    projectName:
      "Global Earthquakes - 3D Visualization with Three.js and Observable",
    projectDescription: "",
    projectLink: "https://earthquake-r3f.vercel.app/",
    projectImgSource: "/projects/CreativeCoding/Earthquake.png",
    tools: ["Three.js, React.js"],
    titleTag: "code creatively",
    date: "2023-03-01",
  },
  {
    projectName:
      "Stitching Heart, Blooming Flowers",
    projectDescription: "",
    projectLink: "https://beating-heart-phi.vercel.app/",
    projectImgSource: "/projects/CreativeCoding/R3f-Heart.png",
    tools: ["Three.js, React.js"],
    titleTag: "code creatively",
    date: "2023-02-01",
  },
  {
    projectName:
      "Spike Planet",
    projectDescription: "",
    projectLink: "https://spikey-planet.vercel.app/",
    projectImgSource: "/projects/CreativeCoding/R3f-spikey.png",
    tools: ["Three.js, React.js"],
    titleTag: "code creatively",
    date: "2023-03-01",
  },
  {
    projectName:
      "Number of Chinese Company Infrastructure in the US and Abroad.",
    projectDescription: "",
    projectLink: "https://twitter.com/tu_yukun/status/1646917464767225862/photo/1",
    projectImgSource: "https://pbs.twimg.com/media/FtcYkEzXoAAxtcw?format=png&name=medium",
    tools: ["Observable"],
    titleTag: "charts",
    date: "2023-04-01",
  },
  {
    projectName:
      "Number of Middle Age Himalayan Climbers Is Increasing Over Time",
    projectDescription: "",
    projectLink: "https://observablehq.com/@tututwo/himalayan-ridge",
    projectImgSource: "/projects/Charts/d3_Himalayan.png",
    tools: ["Observable"],
    titleTag: "charts",
    date: "2022-01-01",
  },
  {
    projectName: "Recreate: Why teachers are walking out of the classroom",
    projectDescription: "",
    projectLink: "https://teacher-svelte.netlify.app/",
    projectImgSource: "/projects/Charts/svelte_teacherSalary.png",
    tools: ["Svelte", "D3"],
    titleTag: "charts",
    date: "2021-07-01",
  },
  {
    projectName: "Covid Monitoring Dashboard - China",
    projectDescription: "",
    projectLink: "https://www.chinacovidmonitor.org/",
    projectImgSource: "/projects/Charts/svelte-covid-cn.png",
    tools: ["Svelte", "D3", "R"],
    titleTag: "charts",
    date: "2022-08-01",
  },
  {
    projectName:
      "How dry would each state be if Americans only consumed local state-produced beer?",
    projectDescription:
      "Geofacetted stack bar chart that compares the beer production and beer consumption in each statevisuals.",
    projectLink:
      "https://twitter.com/tu_yukun/status/1281702418581827584/photo/1",
    projectImgSource: "/projects/Charts/tt_Beer_Produciton.png",
    tools: ["R"],
    titleTag: "charts",
    date: "2020-12-10",
  },
  {
    projectName:
      "How much money did award-winning shows earn before the award date?",
    projectDescription:
      "Exploring the net gross and days before the awarding date of each musical that debutted after 1986",
    projectLink: "https://twitter.com/tu_yukun/status/1297733577849765888/photo/1",
    projectImgSource: "/projects/Charts/tt_Broadway.png",
    tools: ["R"],
    titleTag: "charts",
    date: "2021-01-10",
  },
  {
    projectName: "CSS Doodle Chinese Pattern",
    projectDescription: "",
    projectLink: "https://codepen.io/collection/LPePxy",
    projectImgSource: "/projects/CreativeCoding/css-doodle-纹样.png",
    tools: ["CSS"],
    titleTag: "code creatively",
    date: "2021-12-02",
  },
  {
    projectName: "Rotating 3D Cubes",
    projectDescription: "",
    projectLink:
      "https://observablehq.com/@tututwo/three-js-animated-cubes?collection=@tututwo/three-js-creative-coding-practice",
    projectImgSource: "/projects/CreativeCoding/Observable_GR_animateCubes.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2021-01-02",
  },
  {
    projectName: "Sunset Blob",
    projectDescription: "",
    projectLink:
      "https://observablehq.com/@tututwo/the-annual-ring-v2?collection=@tututwo/three-js-creative-coding-practice",
    projectImgSource: "/projects/CreativeCoding/Observable_GR_blobRing.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2021-01-09",
  },
  {
    projectName: "Rough Fried Eggs",
    projectDescription: "",
    projectLink:
      "https://observablehq.com/d/1d6edd39edb160e7?collection=@tututwo/three-js-creative-coding-practice",
    projectImgSource:
      "/projects/CreativeCoding/Observable_GR_circlePackingMerging.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2021-02-09",
  },
  {
    projectName: "Lili Pads",
    projectDescription: "",
    projectLink:
      "https://observablehq.com/d/86bf42953f2582bd?collection=@tututwo/three-js-creative-coding-practice",
    projectImgSource: "/projects/CreativeCoding/Observable_GR_lotusLeave.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2021-01-19",
  },
  {
    projectName: "Rough Squares",
    projectDescription: "",
    projectLink: "https://observablehq.com/@tututwo/rough-canvas-squares",
    projectImgSource: "/projects/CreativeCoding/Observable_GR_roughSquare.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2021-01-01",
  },
  {
    projectName: "GLSL SDF Practice Collection",
    projectDescription: "",
    projectLink: "https://observablehq.com/collection/@tututwo/sdf",
    projectImgSource: "/projects/CreativeCoding/Observable_SDF.png",
    tools: ["GLSL"],
    titleTag: "code creatively",
    date: "2022-08-01",
  },
  {
    projectName: "Star Candy Ball",
    projectDescription: "",
    projectLink: "https://observablehq.com/d/027525671baa52b4",
    projectImgSource: "/projects/CreativeCoding/Observable-Star.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2022-12-01",
  },
  {
    projectName: "Flow Field 2D",
    projectDescription: "",
    projectLink: "https://observablehq.com/d/73794013ffa23a9c?collection=@tututwo/three-js-creative-coding-practice",
    projectImgSource: "/projects/CreativeCoding/Observable-flowfield.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2023-01-31",
  },
  {
    projectName: "Unfold a Chinese Lattern",
    projectDescription: "",
    projectLink: "https://observablehq.com/@tututwo/chinese-lantern",
    projectImgSource: "/projects/CreativeCoding/Observable_lattern.png",
    tools: ["Observable"],
    titleTag: "code creatively",
    date: "2021-07-01",
  },
  {
    projectName: "Canvas Lightning",
    projectDescription: "",
    projectLink: "https://observablehq.com/@tututwo/lightning",
    projectImgSource: "/projects/CreativeCoding/Observable_lightning.png",
    tools: ["GLSL"],
    titleTag: "code creatively",
    date: "2021-10-01",
  },
  {
    projectName: "Kois",
    projectDescription: "",
    projectLink: "https://observablehq.com/@tututwo/kois",
    projectImgSource: "/projects/CreativeCoding/Observable_kois.png",
    tools: ["Canvas"],
    titleTag: "code creatively",
    date: "2022-09-10",
  },
  {
    projectName:
      "Developing and undeveloped countries remain to be the agricultural countries, made in QGIS",
    projectDescription: "",
    projectLink: "https://datawrapper.dwcdn.net/VjDoq/5/",
    projectImgSource: "/projects/Maps/map_datawrapper_agriculture.png",
    tools: ["Datawrapper"],
    titleTag: "maps",
    date: "2020-12-10",
  },
  {
    projectName: "China Elevation",
    projectDescription: "",
    projectLink: "/projects/Maps/map_elevation_ridge.png",
    projectImgSource: "/projects/Maps/map_elevation_ridge.png",
    tools: ["QGIS", "Adobe Illustrator"],
    titleTag: "maps",
    date: "2020-10-17",
  },
  {
    projectName: "Most buildings in Manhattan were built before 1960s",
    projectDescription: "",
    projectLink: "/projects/Maps/map_Manhattan.png",
    projectImgSource: "/projects/Maps/map_Manhattan_cover.png",
    tools: ["QGIS"],
    titleTag: "maps",
    date: "2020-12-27",
  },
  {
    projectName: "Sichuan Basin Elevation",
    projectDescription: "",
    projectLink: "https://observablehq.com/d/299f845c1c4ba8fe",
    projectImgSource: "/projects/Maps/map_ridgelineSichuan.png",
    tools: ["Observable"],
    titleTag: "maps",
    date: "2022-01-27",
  },
  {
    projectName: "The elevation of Jiangxi Province",
    projectDescription: "",
    projectLink: "/projects/Maps/map_shuimomap_shuimo.png",
    projectImgSource: "/projects/Maps/map_shuimomap_shuimo_cover.png",
    tools: ["QGIS"],
    titleTag: "maps",
    date: "2020-11-07",
  },
  {
    projectName: "Two Dragons of China",
    projectDescription: "",
    projectLink: "/projects/Maps/map_twodragons.png",
    projectImgSource: "/projects/Maps/map_twodragons_cover.png",
    tools: ["QGIS"],
    titleTag: "maps",
    date: "2020-11-27",
  },
]);
